### ISSUE TITLE
Compilation error with graphql-api v0.28.0+

### ISSUE THREAD

**Issue by nsine** [accounts-js/accounts#1046]
# Bug report

## Describe the bug

After upgrading all packages to v0.29.0 (the issue is on 0.28.0 too), I'm getting this error:

```
../../node_modules/@accounts/graphql-api/lib/modules/accounts-password/index.d.ts(16,112): error TS2344: Type 'Partial<{ [key: string]: GraphQLScalarType | IEnumResolver | IResolverOptions<any, any, any> | Partial<IResolverObject<any, any, any>> | (() => any); }>' does not satisfy the constraint 'Partial<{ [key: string]: GraphQLScalarType | IEnumResolver | IResolverOptions<any, any, any> | (() => any) | Partial<IResolverObject<any, any, any>>; }>'.
  Index signatures are incompatible.
    Type 'GraphQLScalarType | IEnumResolver | IResolverOptions<any, any, any> | Partial<IResolverObject<any, any, any>> | (() => any)' is not assignable to type 'GraphQLScalarType | IEnumResolver | IResolverOptions<any, any, any> | (() => any) | Partial<IResolverObject<any, any, any>>'.
      Type 'IResolverOptions<any, any, any>' is not assignable to type 'GraphQLScalarType | IEnumResolver | IResolverOptions<any, any, any> | (() => any) | Partial<IResolverObject<any, any, any>>'.
        Type 'IResolverOptions<any, any, any>' is not assignable to type 'Partial<IResolverObject<any, any, any>>'.
```

when compiling the app. Seems to be some incompatibility between `graphql-modules` which are still on `graphql-tools` v5 and accounts' `graphql-api` which are on v6.

## To Reproduce

1) upgrade "@accounts/graphql-api" at least to v0.28.0
2) compile the app

## Expected behavior

no errors during compilation

## System information

- Version of accounts-js: 0.29.0
- "@graphql-modules/core": "^0.7.17",

**Comment by agustif** [comment]
Hi @nsine, can you try with latest builds of modules/tools?

this is my package.json
```package.json
{
  "name": "@firmas/api",
  "version": "0.1.0",
  "description": "A GraphQL API Server to create and sign PDF Documents.",
  "main": "src/index.ts",
  "scripts": {
    "prod": "pm2 start ts-node --name firmas_api -- --transpile-only ./src/index.ts",
    "dev": "nodemon",
    "start": "ts-node --transpile-only ./src/index.ts",
    "build": "tsc -p tsconfig.json",
    "docs": "typedoc --out docs src --ignoreCompilerErrors",
    "test": "jest"
  },
  "author": "Agusti Fernandez",
  "license": "ISC",
  "dependencies": {
    "pg": "^8.3.0",
    "dotenv": "^8.2.0",
    "express": "5.0.0-alpha.8",
    "typeorm": "0.3.0-rc.19",
    "type-graphql": "^1.0.0-rc.3",
    "@accounts/server": "^0.29.0",
    "@accounts/typeorm": "^0.29.0",
    "@accounts/password": "^0.29.0",
    "@graphql-tools/merge": "6.0.17-alpha-5c3f1a45.0",
    "graphql-subscriptions": "^1.1.0",
    "@accounts/graphql-api": "^0.29.0",
    "apollo-server-express": "2.16.1",
    "@graphql-modules/di": "^0.7.18-alpha-6c93635.67",
    "@graphql-modules/core": "^0.7.18-alpha-6c93635.67"
  },
  "devDependencies": {
    "pm2": "^4.4.0",
    "dotenv": "^8.2.0",
    "nodemon": "^2.0.4",
    "graphql": "^15.3.0",
    "ts-node": "^8.10.2",
    "typedoc": "^0.17.8",
    "@types/pg": "^7.14.4",
    "@types/node": "14.0.27",
    "class-validator": "^0.12.2",
    "@accounts/types": "^0.29.0",
    "reflect-metadata": "^0.1.13",
    "typescript": "^4.1.0-dev.20200808"
  }
}
```

**Comment by nsine** [comment]
will return soon to my attempts to upgrade that and will try this beta version
thanks @agustif !

**Comment by nsine** [comment]
@agustif still doesn't work 😕
Not sure how this graphql-modules version works for you because it still uses old "@graphql-toolkit/*" and graphql-tools v5 (i think this is the reason of incompatibility 🤷‍♂️)

**Comment by nsine** [comment]
well i think i solved this one. Not really a problem of accounts.js, but of having multiple version of the thing which is `graphql-tools`. Funny thing is - we have 3 different major of graphql-tools in our project 😅. `graphql-tools@4` required by apollo-server, `graphql-tools@5` required by accounts-js/graphql-api and `@graphql-tools/*@6` used by us 😆
While we don't use v4 provided by apollo-server - it's still installed and for some reason it overwrites v5 which is needed for accounts
Yeah, yeah that's crazy
![madness](https://media.giphy.com/media/XoWvzO2gYjqpUrjCRl/giphy.gif) 

So the solution for me was to use yarn resolutions to force-replace `graphql-tools` with correct version
```json
// package.json

"resolutions": {
  "apollo-server/graphql-tools": "^5.0.0"
}
```

thanks @agustif for sharing his package.json and giving the hint on that 😘
